-- MySQL Script generated by MySQL Workbench
-- Sun Dec  4 20:47:22 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bank_products
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bank_products` ;

-- -----------------------------------------------------
-- Schema bank_products
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bank_products` DEFAULT CHARACTER SET utf8 ;
USE `bank_products` ;

-- -----------------------------------------------------
-- Table `bank_products`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_products`.`client` (
  `id` INT NOT NULL,
  `firstName` VARCHAR(40) NOT NULL,
  `lastName` VARCHAR(40) NOT NULL,
  `email` VARCHAR(65) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank_products`.`productType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_products`.`productType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank_products`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank_products`.`product` (
  `id` INT NOT NULL,
  `balance` FLOAT NULL DEFAULT 0,
  `interest` FLOAT NULL,
  `creationDate` DATE NULL,
  `expirationDate` DATE NULL,
  `type` INT NOT NULL,
  `idClient` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`idClient` ASC) INVISIBLE,
  INDEX `FK_category_idx` (`type` ASC) VISIBLE,
  CONSTRAINT `FK_idClient`
    FOREIGN KEY (`idClient`)
    REFERENCES `bank_products`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_type`
    FOREIGN KEY (`type`)
    REFERENCES `bank_products`.`productType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
